### ISSUE TITLE
Validation function performance issues

### ISSUE THREAD

**Issue by msheller** [FETS-AI/Challenge#10]
In many of my tests, validation metrics consume the lion's share of the compute time, resulting in very long experiment runtimes (e.g. a week+ to converge). This makes it hard to iterate on ideas.

I'd like to propose two ideas to address this:

1. We add a "choose_collaborators_to_validate" function, just like our training equivalent, that allows for controlling how often these functions are run. For example, I may want to aggregate often in order to reduce local weight divergence, but I may want to reduce validation to once every 10 rounds. This would be very easy to implement in the custom assigner, experiment loop, and simulated time calculator.
2. We try to optimize the validation metrics functions themselves. The validation outputs could be cached, then the metrics all computed at once at the end of the round, where we might be able to leverage parallelism/acceleration better.

**Comment by sarthakpati** [comment]
For the short term, I believe adding a function like `choose_collaborators_to_validate` should be way to go. Long term, we could evaluate the optimization in the validation metrics. 

Thoughts?

**Comment by msheller** [comment]
I'm realizing that "best model saving" in openfl may not cleanly support cases where a subset of collaborators validates. In institutional settings, where the number of collaborators is low, I would argue that you only ever should consider a 'best model' one that was validated by all collaborators. In large-scale consumer settings, you can't really do that since only a small % of collaborators participate in a given round.

This leads me to think we should set it as all or nothing: either all collaborators validate or none do. I'll need to look at openfl more closely to see how it handles cases where no metrics are returned other than loss in a given round. Worse comes to worst, we can insert "0" scores on rounds without validation, which should ensure no "best model" is saved on rounds without validation.

@psfoley , @alexey-gruzdev , do you know what the openfl behavior is if validation  metrics are skipped in a given round?

**Comment by psfoley** [comment]
Following up on this thread...the hausdorff metrics were identified as taking the majority of time to compute for each round. The challenge metrics are now computed by default only every other round (this is configurable), and @brandon-edwards has an open PR to [disable the hausdorff metrics entirely](https://github.com/FETS-AI/Challenge/pull/30) for a given experiment that should be merged soon
