### ISSUE TITLE
Error(s) in loading state_dict for FeTSChallengeModel

### ISSUE THREAD

**Issue by Linardos** [FETS-AI/Challenge#42]
Thank you for being generous with your time and organizing this challenge in such a polished manner. I followed the instructions exactly as they are detailed in README and went through your notebook, changing only the dataset path to the one corresponding to my own directory where the MICCAI_FeTS2021_TrainingData is stored. 
However, when I try to run all cells, I am getting this error at the final cell:

![image](https://user-images.githubusercontent.com/26694607/122768658-7be8e300-d2ac-11eb-89ec-2fa200edfbf8.png)

I wonder if anyone else had had this problem so far?

**Comment by sarthakpati** [comment]
I haven't seen this before. Tagging @brandon-edwards @msheller @psfoley @alexey-gruzdev for more clarity.

**Comment by psfoley** [comment]
Thanks @Linardos for reporting this. I haven't run into this particular problem before either. Could you provide more information about your GPU/CUDA version/PyTorch configuration? It appears that this error can occur with older GPUs that don't have [built-in support in the general pypi distribution of PyTorch](https://github.com/pytorch/pytorch/issues/31285), so you may be able to get around this by either installing the PyTorch nightly package or rebuilding it from source per the instructions in the linked thread.

**Comment by Linardos** [comment]
The GPU is brand new actually, NVIDIA GeForce RTX 3090
CUDA version 11.3 
![image](https://user-images.githubusercontent.com/26694607/122924343-56241280-d36e-11eb-9d5c-78f48112a9a4.png)

PyTorch configuration is set-up by the "pip install ." command as per the instructions, so the versions should be as expected
![image](https://user-images.githubusercontent.com/26694607/122924864-e95d4800-d36e-11eb-8fd8-b8283af03b09.png)

**Comment by sarthakpati** [comment]
Hi @Linardos,

Could you try the CUDA 11.1 installation for PyTorch?

```
pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
```

After that, you can try the following to check if torch is able to see the GPU:

```
python -c "import torch as t; print(t.cuda.is_available())"
```

**Comment by Linardos** [comment]
Hey, this solved it! Thanks a lot sarthak. So it was the CUDA version after all

**Comment by szho42** [comment]
we had the same issue with cuda version 11.0 and on A100.
---
NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     

using torch 1.9.0-cu111 solved the problem.
