### ISSUE TITLE
what does t1ce image mean?

### ISSUE THREAD

**Issue by dskhanirfan** [FETS-AI/Challenge#6]
The exact MRI data consists of a native T1-weighted scan (T1), a native T2-weighted scan (T2), and a T2 Fluid Attenuated Inversion Recovery (T2-FLAIR) scan. what is t1ce data?

**Comment by dskhanirfan** [comment]
contrast enhanced t1

**Comment by sarthakpati** [comment]
Hi,

Thank you for your interest in the FeTS Challenge!

T1CE is the [T1-weighted post-contrast image](https://mrimaster.com/characterise%20image%20t1%20%20post.html). Please reach out if you have more questions!
